language: node
services:
    - docker  
before_install:
    - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
script:
    - chmod +x build.sh
    - chmod +x deploy.sh
    - ./build.sh
    - ./deploy.sh