FROM bitnami/apache:latest
COPY ./vhost.prod.conf /vhosts/my_vhost.conf
COPY ./app /app
COPY ./httpd.conf /opt/bitnami/apache/conf/
CMD echo "Running on port: ${APACHE_HTTP_PORT_NUMBER}";/opt/bitnami/scripts/apache/run.sh