version: '3.7'

services:
  gateway:
    image: 'bitnami/apache:latest'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
        - "./app:/app"
        - "./vhost.conf:/vhosts/my_vhost.conf:ro"
    links:
        - "debianrepo"
  debianrepo:
    build:
      context: '.'
      dockerfile: './debian/Dockerfile'
  archrepo:
    build:
      context: '.'
      dockerfile: './arch/Dockerfile'
  centosrepo:
    build:
      context: '.'
      dockerfile: './centos/Dockerfile'