version: '3.7'

services:
  gateway:
    image: 'bitnami/apache:latest'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
        - "./app:/app"
        - "./vhost.conf:/vhosts/my_vhost.conf:ro"
    links:
        - "debianrepo"
  debianrepo:
    build:
      dockerfile: './Dockerfile.debian'
      context: '.'
  archrepo:
    build:
      dockerfile: './Dockerfile.arch'
      context: '.'
  centosrepo:
    build:
      dockerfile: './Dockerfile.centos'
      context: '.'